perl:
  - "5.18"
  - "5.8"
before_install: git submodule update --init
script: "make test"
notifications:
  email:
    - wakaba@suikawiki.org
  irc:
    channels:
      - "suika.suikawiki.org#mechanize"
    use_notice: true
