=head1 NAME

Web::Encoding - Web Encodings APIs

=head1 DESCRIPTION

This module is a placeholder for Perl APIs for handling Web Encodings.
This module is work in progress; its interface might or might not be
changed later.

=head1 FUNCTIONS

Following functions are exported by C<use>ing the C<Web::Encoding>
module:

=over 4

=item $name = encoding_label_to_name $label

Find the encoding identified by the specified label.  As does Encoding
Standard's "get an encoding" steps, this function ignores leading and
trailing spaces, and compares labels case-insensitively.  The function
returns the encoding name, if found, or C<undef>.

=item $name = fixup_html_meta_encoding_name $name

Replace encoding name for the purpose of HTML character encoding
declaration, as in "prescan a byte stream to determine its encoding"
and "change the encoding" algorithms.  The argument must be an
encoding name (not a label).  The function returns an encoding name.

=item $label = encoding_name_to_compat_name $name

Replace an encoding name to its compatibility name as used in
C<characterSet> or C<inputEncoding> attributes of the C<Document>
interface.  The argument must be an encoding name (not a label).  The
function returns an encoding label or the string C<replacement>.

=item $boolean = is_ascii_compat_encoding_name $name

Return whether the specified encoding is an ASCII-compatible character
encoding or not.  The argument must be an encoding name in the
Encoding Standard, otherwise the result might be wrong.

=item $boolean = is_encoding_label $label

Return whether the specified label identifies an encoding or not.  It
compares labels case-insensitively.  Unlike the
C<encoding_label_to_name> function, however, this function does not
ignore spaces.

=item $name = locale_default_encoding_name $tag

Return the default character encoding name for the specified locale
language tag.  If no default is known for the specified locale,
C<undef> is returned.  The input must be either BCP 47 language tag or
C<*>.  The language tag must be the primary language tag only,
C<zh-TW>, or C<zh-CN>, otherwise no data is available.  The tags are
ASCII case-insensitive.  If C<*> is specified, the global default
encoding name that can be used when locale is not known or the locale
has no default is returned.

=back

Note that the encoding name in the Encoding Standard is not compatible
with Perl L<Encode> module's encoding names.

=head1 SPECIFICATIONS

Encoding Standard <https://encoding.spec.whatwg.org/>.

HTML Standard <https://html.spec.whatwg.org/>.

DOM Standard <https://dom.spec.whatwg.org/>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2011-2014 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
