=head1 NAME

Web::Encoding::UnivCharDet - Universal Detector implementation in Perl

=head1 SYNOPSIS

  use Web::Encoding::UnivCharDet;
  
  $det = Web::Encoding::UnivCharDet->new;
  $charset = $det->detect_byte_string ($bytes);

=head1 DESCRIPTION

The C<Web::Encoding::UnivCharDet> module is a character encoding
detector for byte strings.

It is a Perl port of Mozilla universalchardet (or universal detector)
but has been modified to support more encoding and to improve
accuracy, as required for compatibility with existing Web content.

=head1 METHODS

Following methods are available:

=over 4

=item $det = Web::Encoding::UnivCharDet->new ($mode, prefer_cjk => boolean)

Return a new instance of the universal detector.

The argument I<$mode> can be specified to set the mode of the
detection.  It can be one of C<all> (all supported encodings), C<web>
(for HTML pages; default if omitted), or C<zip> (for ZIP file names).

The key/value pair C<prefer_cjk> can be specified to set whether
inputs will come from a CJK source (e.g. the request's origin's TLD is
a ccTLD of CJK countries).  If specified to a true value, the detector
is biased to CJK encodings for short inputs (such as file names).  It
has little effect for long inputs with enough non-ASCII bytes.

=item $charset = $det->detect_byte_string ($bytes)

Return the detected encoding name of the given byte string.  If it
can't detect the encoding, the method returns C<undef>.  Otherwise it
returns an encoding label.

Returned encoding names are in lowercase.

=back

=head1 SUPPORTED ENCODINGS

The set of supported character encodings (i.e. possible values
returned by C<detect_byte_string) method) vary depending on the mode
of the detector specified when the instance is created.

1. Detectable in C<all>, C<web>, and C<zip> modes

  Encodings specified by the Encoding Standard :

    big5 euc-jp euc-kr gb18030 ibm866 iso-8859-7 shift_jis utf-8
    windows-874 windows-1250 windows-1251 windows-1252 windows-1253
    windows-1255

  Encodings not specified by the Encoding Standard :

    ascii

The ascii encoding is special; it is returned when the input has no
non-ASCII character.  In the Encoding Standard, C<ascii> is one of the
encoding labels of windows-1252.

Note that the C<undef> value (I<not> the string of that value) can be
returned when no encoding seems better than any other known encoding.

2. Detectable in C<all> and C<web> modes

  Encodings specified by the Encoding Standard :

    iso-2022-jp iso-8859-2 iso-8859-3 iso-8859-4 iso-8859-6 iso-8859-8
    iso-8859-10 iso-8859-13 koi8-r utf-16be utf-16le macintosh
    x-mac-cyrillic

In C<web> mode, utf-16be and utf-16le are only detectable by BOM.  In
C<all> mode, UTF-16 without BOM are also detectable where possible.

  Encodings not specified by the Encoding Standard :

    armscii-8 georgian-academy georgian-ps tscii tab viscii x-viet-vni
    x-viet-vps x-viet-tcvn

3. Detectable in C<all> and C<zip> modes

  Encodings not specified by the Encoding Standard :

    ibm437 ibm737 ibm775 ibm850 ibm852 ibm855 ibm857 ibm862 ibm865

4. Detectable in C<all> mode

  Encodings specified by the Encoding Standard :

    iso-8859-5 iso-8859-15 iso-8859-16

  Encodings not specified by the Encoding Standard :

    iso-2022-cn iso-2022-kr hz-gb-2312 x-euc-tw johab utf-32be
    utf-32le x-iso-10646-ucs-4-3412 x-iso-10646-ucs-4-2143 tam
    x-mac-ce

Though the Encoding Standard defines encoding labels C<iso-2022-cn>,
C<hz-gb-2312>, and C<iso-2022-kr>, they are associated with the
replacement encoding such that they cannot be effectively used in the
environments where the Encoding Standard is applied.

=head1 DEPENDENCY

This module requires Perl 5.8 or later.  No additional module is
required.

=head1 SEE ALSO

[HTML] HTML Standard
<https://www.whatwg.org/specs/web-apps/current-work/#encoding-sniffing-algorithm>.

[ENCODING] Encoding Standard <https://encoding.spec.whatwg.org/>.

[UNIVCHARDET] "A composite approach to language/encoding detection",
S. Li, K. Momoi, Proceedings of the 19th International Unicode
Conference
<https://www-archive.mozilla.org/projects/intl/universalcharsetdetection>.

[MOZILLAUNIVDET] universalchardet in Mozilla repository.  This
implementation derives from Mozilla's C++ implementation as of 1 May
2013
<https://hg.mozilla.org/mozilla-central/archive/c0e81c0222fc.zip>.

[MOZILLAUNIVDETBOM] "Make Universal Charset Autodetector recognise UTF
by BOM", Alexey Chernyak, 3 Nov 2005
<https://github.com/mozilla/gecko-dev/commit/68332f717f14e8f2467ca4f2c521ed8fe6eff71d>.

[CHARDET] "Chardet: The Universal Character Encoding Detector"
<https://github.com/chardet/chardet>.

[CHARDETMAC] "Added a prober for MacRoman encoding.", Rob Speer, 29
Jun 2022
<https://github.com/chardet/chardet/commit/c292b52a97e57c95429ef559af36845019b88b33>.

[CHARADE13] "Support CP949, fixes #10", puzzlet, 25 Jan 2013
<https://github.com/sv24-archive/charade/pull/13/files>.

[SWUNIVERSALCHARDET] "UniversalCharDet", SuikaWiki authors
<https://wiki.suikawiki.org/n/UniversalCharDet>.

[SWDETECTION] "文字コードの決定", SuikaWiki authors
<https://wiki.suikawiki.org/n/%E6%96%87%E5%AD%97%E3%82%B3%E3%83%BC%E3%83%89%E3%81%AE%E6%B1%BA%E5%AE%9A$27942>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 ACKNOWLEDGEMENTS

Thanks to the authors and contributors of Mozilla's original universal
detector implementation [MOZILLAUNIVDET] and its variants
[MOZILLAUNIVDETBOM] [CHARADE13] [CHARDET] [CHARDETMAC], from which the
Perl port derives.

=head1 LICENSE

This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

Note that some of files are licensed with different terms.  See their
documentations.

=cut
