=head1 NAME

Web::Encoding::UnivCharDet - Universal Detector implementation in Perl

=head1 SYNOPSIS

  use Web::Encoding::UnivCharDet;
  
  $det = Web::Encoding::UnivCharDet->new;
  $charset = $det->detect_byte_string ($bytes);

=head1 DESCRIPTION

The C<Web::Encoding::UnivCharDet> module is a Perl port of Mozilla
universalchardet (or universal detector) for autodetecting character
encoding of byte strings.

=head1 METHODS

Following methods are available:

=over 4

=item $det = Web::Encoding::UnivCharDet->new

Return a new instance of the universal detector.

=item $det->filter->{utf} = Boolean (default: false)

If true, the UTF-32 and UTF-16 detection is enabled.  Otherwise, it is
disabled.

=item $charset = $det->detect_byte_string ($bytes)

Return the detected encoding name of the given byte string.  If it
can't detect the encoding, the method returns C<undef>.  Otherwise it
returns an encoding label.

In the default configurations, one of the following encoding labels
are returned:

  utf-8 utf-16be utf-16le iso-2022-cn big5 x-euc-tw gb18030 hz-gb-2312
  iso-2022-jp shift_jis euc-jp iso-2022-kr euc-kr iso-8859-5 koi8-r
  windows-1251 x-mac-cyrillic ibm866 ibm855 iso-8859-7 tis-620
  windows-1253 iso-8859-8 windows-1255 windows-1252 macintosh

Note that C<x-euc-tw> and C<ibm855> are not supported by the Encoding
Standard.  Encoding labels C<iso-2022-cn>, C<hz-gb-2312>, and
C<iso-2022-kr> are supported but associated with the replacement
encoding.

If the UTF-32 and UTF-16 detection is enabled, one of the following
encoding labels might also be returned:

  utf-32be utf-32le x-iso-10646-ucs-4-3412 x-iso-10646-ucs-4-2143
  utf-16be utf-16le

Note that labels other than C<utf-16be> and C<utf-16le> are not
supported by the Encoding Standard.

Returned encoding names are in lowercase.

=back

This module only exposes limited functionality of the original
universal detector.  If there are compelling use cases for more
features, such as confidence, they could be exposed in future revision
of this module.

=head1 DEPENDENCY

This module requires Perl 5.8 or later.  No additional module is
required.

=head1 SPECIFICATIONS

[HTML] HTML Standard
<https://www.whatwg.org/specs/web-apps/current-work/#encoding-sniffing-algorithm>.

The detector is expected to be used as part of the HTML encoding
sniffing algorithm, as defined by the HTML Standard.

[ENCODING] Encoding Standard <https://encoding.spec.whatwg.org/>.

The Encoding Standard defines how to decode the byte string using the
detected encoding name.  (Note that C<ibm855> and C<x-euc-tw> is not
defined in the Encoding Standard at the time of writing.)

=head1 SEE ALSO

[UNIVCHARDET] "A composite approach to language/encoding detection",
S. Li, K. Momoi, Proceedings of the 19th International Unicode
Conference
<https://www-archive.mozilla.org/projects/intl/universalcharsetdetection>.

[MOZILLAUNIVDET] universalchardet in Mozilla repository.  This
implementation derives from Mozilla's C++ implementation as of 1 May
2013
<https://hg.mozilla.org/mozilla-central/archive/c0e81c0222fc.zip>.

[MOZILLAUNIVDETBOM] "Make Universal Charset Autodetector recognise UTF
by BOM", Alexey Chernyak, 3 Nov 2005
<https://github.com/mozilla/gecko-dev/commit/68332f717f14e8f2467ca4f2c521ed8fe6eff71d>.

[CHARDET] "Chardet: The Universal Character Encoding Detector"
<https://github.com/chardet/chardet>.

[CHARDETMAC] "Added a prober for MacRoman encoding.", Rob Speer, 29
Jun 2022
<https://github.com/chardet/chardet/commit/c292b52a97e57c95429ef559af36845019b88b33>.

[CHARADE13] "Support CP949, fixes #10", puzzlet, 25 Jan 2013
<https://github.com/sv24-archive/charade/pull/13/files>.

[SWUNIVERSALCHARDET] "UniversalCharDet", SuikaWiki authors
<https://wiki.suikawiki.org/n/UniversalCharDet>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 ACKNOWLEDGEMENTS

Thanks to the authors and contributors of Mozilla's original universal
detector implementation [MOZILLAUNIVDET] and its variants
[MOZILLAUNIVDETBOM] [CHARADE13] [CHARDET] [CHARDETMAC], from which the
Perl port derives.

=head1 LICENSE

This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

Note that some of files are licensed with different terms.  See their
documentations.

=cut
